### ISSUE TITLE
Copy open issues from mdw GitLab

### ISSUE THREAD

**Issue by magrawa** [CenturyLinkCloud/MDW#1]
Labels/Projects/Milestones have been created already.
Only copy mdw6 issues.  MDW 5.5 issues will be migrated to corporate GitLab.

**Comment by PabitraKumar-Behera** [comment]
Subject |  Created By | APP Name | Replies | Last Updated | Priority | Owner | Resolution | Target Build  
--------------------------------------------- | -------- | -------- | ---------------------- | -------- | --------------- | -------- | -------- | -----------

CCWF instances moving to RHEL5 servers, Discovery method | Best, Andrew | CCWF | 1 | 42816.7291666667 | (2) Normal |  |  | 
Attributes missing in Manual Task in 5.5 | Kumar, Mithlesh | DSP | 0 | 42816.3583333333 | (2) Normal | Sheets, Morgan |  | 
Regression Test (Event notification) | Kandoor, Nagaraj G | DSP | 3 | 42816.3819444444 | (2) Normal | Behera, PabitraKumar |  | 
Facing issues with com.centurylink.mdw.workflow.adapter.mqseries.MqSeriesAdapter | Srivastava, Arpita | DGW | 3 | 42816.2513888889 | (1) High | Brojde, Jack |  | 
Need to Add new PPT (Pre Production Test) Env. in MDW designer RCP | Karan, Umesh | IOM | 1 | 42811.0729166667 | (2) Normal | Bellamkonda, Naveena | Other | 
Have to Reinstall daily | Mckee, Michele M | WFMT | 1 | 42810.4291666667 | (1) High | Bellamkonda, Naveena |  | 
Getting Exception message DSP_2017 is not resolved | Chandramowliswaran, Shivashankar | DSP 5.5 | 7 | 42811.4576388889 | (2) Normal | Agrawal, Manoj |  | 
Regarding Hold and Release completion codes in 5.5 | Vummadi, Jaipal Reddy | DSP | 2 | 42814.2715277778 | (1) High | Sheets, Morgan |  | 
ConnectException: Connection timed out: connect | Munjal, Vikram | MOB | 2 | 42811.61875 | (1) High | Agrawal, Manoj |  | 
Sync Asset Archive not working | Mckee, Michele M | WFMT | 9 | 42811.1729166667 | (2) Normal | Bellamkonda, Naveena |  | 
Not able to stub the adapter activity in groovy script. | Varshney, Rajat Kumar | DGW | 10 | 42811.3381944444 | (2) Normal | Behera, PabitraKumar |  | 
Remote Central | Wells, Barry | OMNIVue | 1 | 42801.7152777778 | (2) Normal | Oakes, Donald |  | 
Not able to view Admin UI under MDW WF extensions in eclipse | Karan, Umesh | IOM | 1 | 42801.2118055556 | (2) Normal | Bellamkonda, Naveena |  | 
PROCESS_INSTANCE tale is empty.. Unable to process Task_instance tables | Wells, Barry | OMNIVue | 3 | 42800.7256944444 | (1) High | Brojde, Jack |  | 
OMNIVUE - Document table 185 million rows | Wells, Barry | OMNIVue | 4 | 42801.5291666667 | (1) High | Brojde, Jack |  | 
How to read the PackageVO from Drools function | Ayyadurai, Mugundhan | DSP | 7 | 42803.4229166667 | (2) Normal | Brojde, Jack |  | 
can't successfully deploy the MDW6 demp project | Karan, Umesh |  | 1 | 42795.3743055556 | (2) Normal | Sheets, Morgan |  | 
DVAR PO Shutdown not clean in EWS | Basrur, Rajesh | DVAR-PO | 2 | 42761.5784722222 | (2) Normal | Agrawal, Manoj |  | 
Shut down application is not working | Jiao, Hua | DOCSWF | 9 | 42677.9861111111 | (2) Normal | Brojde, Jack |  |

**Comment by donaldoakes** [comment]
Pabitra, thanks for taking on this issue.  I've created the Projects, Labels and Milestones.  I've also closed a number of issues that don't need to be ported over. - Don

**Comment by magrawa** [comment]
Please migrate issue from MDW GitLab (http://ne1itcprhas51.corp.intranet/mdw/mdw) not from SharePoint.

**Comment by PabitraKumar-Behera** [comment]
| Subject | Author | Assignee | Milestone | Label |
| : ------------------------------ | : ---------------------------- | : ---------------------------- | ---------------------------- : | ---------------------------- : | 
 | When creating a New MDW Process, the Finish button is greyed out   | Morgan.Sheets     |  | 9.x   |  Defect Designer  | 
 | ExternalEventHandler File Naming   |  Donald Oakes     |  | 9.1.3   |  Designer Enhancement  | 
 | Fix duplicate external event handler creation on click of save   | Naveena Bellamkonda    |   | 9.1.3    | Defect Designer u | 
 | Fix AutoForm manual task template anomalies   | Donald Oakes     |  | 9.1.3    | Defect Designer  | 
 | More flexible adapter/activity stubbing   | Donald Oakes     |  | 9.x    | Designer Enhancement  | 
 | Swagger and Browser issues   | Iain Bisset     |  | 6.0.02    | MDWHub Services  | 
 | Delay handler invocation for process-level SLAs and Commit Dates   |  | Donald Oakes     |  | 6.0.02    | Engine Enhancement Workflow  | 
 | Save protocol headers as part of request and response documents   |  | Donald Oakes     |  | 6.0.02    | Database Enhancement Services  | 
 | Error reports should be sent through a REST service instead of SMTP   |  | Donald Oakes     |  | 9.x    | Designer Enhancement Services  | 
 | Allow missing db configuration for VCS Assets projects   |  | Donald Oakes     |  | 9.x    |  | Designer Enhancement  | 
 | Automated Test modularity enhancements   |  | Donald Oakes     |  | 9.1.3    | Designer Enhancement Services  | 
 | Import remote Git VCS project does not need deep clone   |  | Donald Oakes     |  | 9.x   |  Designer Enhancement  | 
 | Fix buildSrc compilation errors and restore AsyncExecHandler Gradle task.   | Donald Oakes     |  | 6.0.x    | Defect Environment  | 
 | Test Case HTTP support for net proxy config   |  | Donald Oakes     |  | 9.1.3    | Designer Enhancement  | 
 | Debug AutoTest Groovy scripts in Designer   |  Donald Oakes     |  | 9.1.3    | Designer | 
 | Process version discrepancies   | Donald Oakes     |  | 9.x    | Defect Designer  | 
 | Jenkins job to publish javadocs   | Donald Oakes     |  | 6.0.02    | Enhancement Environment  | 
 | Switch mdw-demo to use Gradle instead of Maven   | Donald Oakes     |  | 6.0.02    | Enhancement Environment  | 
 | MDW Open Source Documentation   | Manoj Agrawal  |  |  |  | 
 | Display process and activity markdown documentation in MDWHub   | Donald Oakes     |  | 6.0.02    | Enhancement MDWHub | 
 | igrate Camel capabilities to mdw6  1 | Donald Oakes     |  | 6.0.x    | Enhancement Services Workflow  | 
 | Provide a Bus example in com.centurylink.mdw.demo.camel   |  Donald Oakes     |  | 5.5   |  Enhancement Services  | 
 | Save request/response headers for Listeners and Adapters   |  Donald Oakes     |  | 6.0.02    | Enhancement Services  | 
 | Create Process Heat Map   |  | Manoj Agrawal     |  | 6.0.x    | MDWHub  | 
 | Create Pie Chart reports in MDWHub   | Manoj Agrawal     |  | 6.0.x    | MDWHub  | 
 | Run a process from MDWHub  | Donald Oakes     |  | 6.0.02    | Enhancement MDWHub  | 
 | Custom Gradle task for executing AutoTests  | Donald Oakes     |  | 6.0.02    | Enhancement Workflow  | 
 | Support for deploying on nginx and Jetty stack   | Donald Oakes     |  | 6.0.x    | Enhancement Environment  | 
 | Populate statusCode and statusMessage on service request documents (incoming and outgoing).   | Donald Oakes     |  | 6.0.02    | Engine Enhancement  | 
 | Make Services tab API section work on Fuse   |  Manoj Agrawal     |  | 5.5.40    | Enhancement MDWHub  | 
 | Automated builds for mdw6   |  Donald Oakes     |  | 6.0.x    | Enhancement Environment  | 
 | Docker image for mdw6   |  Donald Oakes     |  | 6.0.x    | Enhancement Environment  | 
 | Service for filtering process instances by variable value   | Donald Oakes     |  | 6.0.02    | Defect Services  | 
 | Fix osgi-service-adapter test case   |  MDW Development    |  |  | Workflow  | 
 | When downloading remote package zips, sometimes a painful workspace refresh is triggered   | Donald Oakes     |  | 9.x    | Designer Enhancement  | 
 | New Manual Task Activity: Fallout Task   | Donald Oakes     |  | 5.5    | Enhancement Workflow  | 
 | Create OAuth Server Instance in AppFog   |  Manoj Agrawal    |  |  | Enhancement Services  | 
 | Substititution in file when sending a noitce   |  Manoj Agrawal    |  |  | Defect Designer  | 
 | Associate related event wait/notify activities in Designer   |  Donald Oakes    |  |  | Designer  | 
 | Task Event Wait registration service   |  Donald Oakes    |  |  | Enhancement Services | 
 | Designer should handle bad or missing com.centurylink.mdw.plugin.xml   | Donald Oakes     |  | 9.x    | Defect Designer  | 
 | Spreadsheet-driven parameterized values in test cases   | Donald Oakes     |  | 9.x    | Designer Enhancement  | 
 | Spring-annotated Dynamic Java   | Donald Oakes    |  |  | Cloud Enhancement  | 
 | Federated Workflow   | Donald Oakes    |  |  | Designer Enhancement Workflow  | 
 | Tag build in Git from Jenkins  | Donald Oakes    |  |  | Environment  | 
 | Update Exlipse plug-in to support pom.xml change in hirearchial project structure   |  Manoj Agrawal    |  |  | Designer Enhancement  | 
 | Get a trusted certificate with a domain like mdw.ctl.io   |  Manoj Agrawal    |  |  | Environment  | 
 | JSF (xhtml) editing   |  Manoj Agrawal    |  |  | Defect Designer |

**Comment by PabitraKumar-Behera** [comment]
I have suppressed the duration of issue opened and when was the last time issue was updated and number of replies. Do we need them in public domain.

**Comment by magrawa** [comment]
Hi Pabitra,
All of the above should be a seperate issues on this repository. Please look at the issue I create this https://github.com/CenturyLinkCloud/MDW/issues/6.
Pay attention to label, projects and Milestones. If there are replies to an issue please attach to this new issue.
Thanks,
Manoj
