### ISSUE TITLE
Populate statusCode and statusMessage on listener response documents

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#11]
Currently this is done for Adapter responses, but not for listeners.  Incoming requests should retain the status codes of responses we sent back.  The columns are DOCUMENT.STATUS_CODE and DOCUMENT.STATUS_MESSAGE. The values are protocol specific, and initially we'll only support HTTP codes and messages.

**Comment by jbrojdeCTL** [comment]
This was completed and included in 6.0.02.   Currently, the status code is set in metaInfo Map (key=HttpStatusCode / Listener.METAINFO_HTTP_STATUS_CODE) by the service, or present in Exception object (metaInfo entry overrides exception code).  Otherwise, defaults to 200 for all methods, which matches what Tomcat will respond with unless specified in metaInfo Map.    If a different success code (i.e. 201, 202, etc.) is desired, the service itself will have to set that in metaInfo Map based on actual type of operation performed and outcome from that operation (i.e. new record was created, existing record modified, etc.).
