### ISSUE TITLE
Process updates not reflected after cache refresh

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#118]
It's been observed (especially in Linux environments) that workflow process updates imported from Git sometimes do not take effect after a cache refresh but only after a server bounce.  Some users also claim that even after a bounce their changes are not reflected (request appears to trigger old process definition).  In this case clearing the Asset Archive and the .temp directory seems to be required.

The scenario involves launching a process from a JsonRestService by calling the WorkflowServices API:
ServiceLocator.getWorkflowServices().invokeServiceProcess("donsproc",
                content, String.valueOf(System.currentTimeMillis()), new HashMap<>(), new HashMap<>());

I've not been able to reproduce this locally.

**Comment by jbrojdeCTL** [comment]
Unless we can reproduce, I really cannot see how we could fix this, since I don't see how this would ever happen unless there's a newer version (by number) of the process somewhere else (such as in Archive or default package), in which case it would launch that other (higher) version of the process.

**Comment by jbrojdeCTL** [comment]
One thing I did notice was an issue launching a process from MDWHub.  First, launch a process.  Then, update process to newer version.  then, click on Definitions list in MDWHub, list of all processes is displayed, including newer version of process.  Select newer version of process.  Click on Run icon.  MDWHub will send request to server still containing previous versions's process ID, instead of newer version's process ID.   Clearing browser's cache/reloading MDWHub clears the issue.
