### ISSUE TITLE
Process/Instance hierarchy in MDWHub

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#177]
Provide these features in MDWHub similar to what we have in Designer.

**Comment by magrawa** [comment]
Hi Jack,

Sorry about the confusion. I will try to explain the scenario.

In TOM we have broken the modules into multiple MicroServices, which call each other. Each MicroService consists of/triggers multiple processes.

When I right click on any process instance and view hierarchy in mdw designer, it will list the calling process and called process instances. But it wont list the calling and called microservices and their process instances. 

Because there are more process instances (than what mdw listed under process hierarchy) belonging to same transaction via MicroService calls, it is convinient to see all of them in the hierarhy results.

So my question was, is there any feature that lists the MicroServices hierarchy. (By Microservices hierarchy, I mean process instances hierarchy under each MicroService)

Let me know if you like to IM or have a short call. Thanks for your response.

Thanks,

Imran

**Comment by jbrojdeCTL** [comment]
With the change in service Designer calls to now call Processes service, it (Processes) now can handle the same functionality to show the process hierarchy, so now it's just a matter of displaying it in Hub.   Search for "callHierarchyFor" in Processes.java.
