### ISSUE TITLE
Suitable error flagging on unsupported subprocess invocations

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#205]
There is a least one scenario where we fail to protect against unsupported config:
 - From a service process, a non-service subflow is invoked with the `synchronous` attribute set to TRUE.

Currently workflow is allowed to proceed under unsupported conditions like this, which has caused confusion from developers about the expected behavior.  We should throw an appropriately-worded exception.

**Comment by jbrojdeCTL** [comment]
For InvokeSubProcessActivity, we decide how to execute the sub process based more on Service/Non-service of current and Sub processes rather than if user selected Sync=yes/no.   Perhaps we need to take that user selection more into account instead of if processes are Service or regular.   I think for InvokeHeterogenous, we don't really care if the child is marked as service or regular, and we drive the decision based on Sync/Parallel selections instead.

**Comment by jbrojdeCTL** [comment]
For a reference of what is allowed and how things will execute under different circumstances, go here http://centurylinkcloud.github.io/mdw/docs/help/SubProcessInvocations/
