### ISSUE TITLE
Slack app routing and general MDW App token cloud routing

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#271]
We need to cloud-based solution for proxying incoming Slack request to distributed MDW endpoints.  We'll deploy one instance in the public cloud to handle this function.

**Comment by jbrojdeCTL** [comment]
In addition to being able to route Slack originated messages to an MDW application, we also need to be able to route MDW originating messages to third-party providers (i.e. Slack).   For this, we will utilize the industry standard of issuing MDW application tokens to interested MDW applications, which they would specify when sending requests to our cloud routing instance.

**Comment by jbrojdeCTL** [comment]
Our public routing instance is Appfog prod, which needs to have the internal "cloud" package deployed in order to work.   The MDW app instance integrating with Slack also needs an MDW App Token in order to authenticate with our AppFog prod instance.   Currently, only our AppFog Dev instance has an MDW App Token.
