### ISSUE TITLE
Handle request timeouts during Git asset import

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#311]
After MDWHub asset import from Git, a server cache refresh is triggered from the client-side.  If the service request to perform the import times out due to server configuration, the import completes as expected on the server, but the subsequent cache refresh never happens.  We should provide an appropriate error message when this occurs.  We could also consider performing the cache refresh from the server side, but this is likely to exacerbate the timeout scenario since a single request would then perform both actions.

To avoid long-running git clones, we could consider implementing shallow clones, which depends on this feature in JGit: https://bugs.eclipse.org/bugs/show_bug.cgi?id=475615.

**Comment by donaldoakes** [comment]
A couple of other thoughts:
 - Hopefully we're not including node_modules in any asset backup step.  We can probably modify the backup to honor .mdwignore (which includes node_modules).
 - We should consider removing the backup copy entirely and rely on Git Fetch instead of a hard reset (enabling us to perform the integrity check).

**Comment by jbrojdeCTL** [comment]
Currently import doesn't do a clone, it does a fetch, hardReset, checkout of branch, and pull.   Also, Don's recent fix to honor .mdwignore when loading the PackageDirs also affects the VcsArchiver backup(), so node_modules will be excluded starting with 6.0.13.     

Fixing the logic used to get "OtherServerURLs" to use ApplicationContext.getServerHost() instead of what the metainfo map has for RequestURL.  This is to prevent propagating to itself.

**Comment by donaldoakes** [comment]
After giving this issue some thought, I'm recalling that it's deemed bad form for the browser to take more than a couple of seconds to respond.  Therefore, for asset imports we should consider a non-realtime response model using websockets (think Travis CI).

**Comment by donaldoakes** [comment]
Made obsolete by #389
