### ISSUE TITLE
FilePanel edit

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#320]
Suppress the Edit icon and restrict server access unless **ALL** of the following conditions are met:
  - User has SiteAdmin role
  - File is text; not binary
  - Editing is enabled in a filepanel config setting
  - File size does not exceed 100k

**Comment by magrawa** [comment]
We are not going to implement this right now because in Paas this is not required and in JWS/FOSS, Web Engg team do not want passwords to show up. One way to implement is to remove the file content when user clicks edit on the file containing passwords and display a message like this
"Please copy paste the updated contents here."

Here are the files which already were modified to update a property file without passwords. 

[FileView.txt](https://github.com/CenturyLinkCloud/mdw/files/1786760/FileView.txt)
[FilePanelService.txt](https://github.com/CenturyLinkCloud/mdw/files/1786761/FilePanelService.txt)
[Toolbar.txt](https://github.com/CenturyLinkCloud/mdw/files/1786762/Toolbar.txt)
