### ISSUE TITLE
MDWHub CLI command console without MDW_HOME

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#327]
If the MDW_HOME environment variable is not set, the Hub CLI console should still work.

**Comment by donaldoakes** [comment]
Fixed.  Needs to be tested in JWS.

**Comment by jbrojdeCTL** [comment]
I think we only have this issue because we specified a non-relative path for mdw.asset.location property: /foss/foss-ews/instances/mdwjws-dev1/current/CenturyLink/mdw-demo/assets.

If we just specify a relative path, then we'll use the project path to fill in the full asset path, and so they should match.
