### ISSUE TITLE
Automated builds for mdw6

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#41]
We want to use Travis CI to continuously build our mdw6 code from GitHub. https://docs.travis-ci.com/user/getting-started/

**Comment by PabitraKumar-Behera** [comment]
It needs to have public GitHub access.

**Comment by magrawa** [comment]
The build is working only issue now is that jsHint is not working. Here is the latest build log
https://travis-ci.org/CenturyLinkCloud/mdw/builds/224461129
I am thinking it is due to the way Travis CI build process is setup. Build starts from the root folder not from mdw folder. so we might have to tweak Gruntfile.js to kick that task. Also we might gte more info if we can figure out how to run Travis build in debug mode.
