### ISSUE TITLE
Support for asset import from Git tags as well as branches

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#492]
This has many implications, and will require extensive analysis.

**Comment by jbrojdeCTL** [comment]
An application can configure MDW to checkout a specific tag instead of a branch (mostly useful for test/prod envs) by removing the mdw.git.branch property and instead using mdw.git.tag property which specifies the name of the tab (i.e. in mdw.yaml:  "git.tag: dec_2018_release".

As a result of running against a tag, users cannot edit/import assets using MDWHub.
