### ISSUE TITLE
Search parent packages for error handler processes

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#493]
When a runtime error is encountered, currently the search for package-level handlers includes only the package of the process instance.  However, if a handler is not found here, we should continue to traverse the parent package hierarchy to locate potential handlers.

This logic can be incorporated into ProcessEngineDriver.getPackageHandler().

**Comment by varunairi** [comment]
Rather than making a heirarchical structure (as there is no "extends" concept and all processes are visible to every package ) , can we rather have a exception handler "type" package. And every business package can be configured to select one of these packages (among all available exception type package names).

**Comment by donaldoakes** [comment]
I think in 6.1.09 we can readily extend the existing hierarchical pattern for error handling to search in parent packages.

We can also open a separate issue to cover your more novel approach of having exception handler type packages.  I would like to explore this in more depth.

**Comment by donaldoakes** [comment]
Feel free to open an issue describing how you'd like exception handler type packages to work.
