### ISSUE TITLE
Externalize Active MQ storage directory in application-context.xml

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#520]
In mdw-common/src/META-INF/mdw/spring/application-context.xml, change the hardwired `amq:broker dataDirectory` to use property syntax like the values in the MDWDataSource bean.  The default dataDirectory when no property is specified should be the existing relative location (`../activemq-data`).

**Comment by jbrojdeCTL** [comment]
New properties:
activemq:
      location: activemq-data   # Has to be relative to startup directory - default=../activemq-data
      port: 61619   # default=61618
      maxConnections: 10   # Max connections in JMS pool - default=8

Unfortunately, there's a problem with Spring Expression Language and the activemq schema that means the expression cannot be the first thing in the value, meaning the following doesn't work:

dataDirectory="#{T(com.centurylink.mdw.config.PropertyManager).getProperty('mdw.activemq.location', '../activemq-data')}">

But it does work if you add a leading space to it (but then the specified path doesn't work because it starts with a space), so instead, we're specifying ./ before the expression like this:

dataDirectory="./#{T(com.centurylink.mdw.config.PropertyManager).getProperty('mdw.activemq.location', '../activemq-data')}">

This means that the specified value via property has to be relative to the startup directory of the application.   This is still better than having to override the entire application-context.xml file
