### ISSUE TITLE
HTTP response status codes on REST requests

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#73]
When a non-zero HTTP response is returned from an mdw6 REST service, this is embedded in the StatusResponse JSON object in payload (whereas old style services would populate this with zero despite the HTTP status code).  We need to make sure Designer handles this.

http://localhost:8080/mdw/Services/Users/abc

**Comment by donaldoakes** [comment]
Also we're not setting the HTTP Response status message correctly, so the following gets a code of 404, but the message (HTTP status message -- not payload message) is "OK".

http://localhost:8080/mdw/Services/Workgroups/abc

**Comment by jbrojdeCTL** [comment]
Naveena, you can refer to the commit mentioned above to get an idea of what we mean.   We need to change Designer to be able to handle codes like 404 when looking for a user that doesn't exists, for example.   This would apply to both the HTTP code in the HttpServletResponse object and also in the payload of the response.   If you pull recent changes, and try  http://localhost:8080/mdw/Services/Users/abc, you will see that both the HTTP code (use browser's dev tools) and the payload both have a status of 404 now instead of 200 for HTTP, and 0 in payload.
