### ISSUE TITLE
Support for MongoDB 4.x

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#845]
Upgrade package `com.centurylink.mdw.mongo` to support MongoDB Community Edition 4.x.

**Comment by jbrojdeCTL** [comment]
Upgraded client driver JARs from 3.6 to 3.12 which is compatible with MongoDBs up to 4.2 and down to 2.6 while still using the pre-3.7 driver way of creating the MongoClient, so no code changes are needed at this time to the MongoDocumentDb implementation of the DocumentDb interface.  Changes will be needed in the future once we need to upgrade the driver to a 4.x version in order to connect to MongoDB 4.4 or later.
